name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Install
      run: cargo install --path wa-monitor
    - name: Run tests
      run: |
        mkdir temp
        cargo test --verbose
